// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBweHeVeM1eBoxNdzCpamp6_iUhKxgWEzk',
    appId: '1:741474883595:web:8ba6db2b43dbe3c9e54f0e',
    messagingSenderId: '741474883595',
    projectId: 'fruit-hub-756d3',
    authDomain: 'fruit-hub-756d3.firebaseapp.com',
    storageBucket: 'fruit-hub-756d3.firebasestorage.app',
    measurementId: 'G-RGW51D8X05',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAERBZCAhKafK9vzZeRAJwow8HuwuVyMvw',
    appId: '1:741474883595:android:710f4a805b62a4ace54f0e',
    messagingSenderId: '741474883595',
    projectId: 'fruit-hub-756d3',
    storageBucket: 'fruit-hub-756d3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC33GFznNZZb1RarVvAB1vUeUU4cV7sTLU',
    appId: '1:741474883595:ios:fa02471a25c51360e54f0e',
    messagingSenderId: '741474883595',
    projectId: 'fruit-hub-756d3',
    storageBucket: 'fruit-hub-756d3.firebasestorage.app',
    iosBundleId: 'com.example.fruitApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC33GFznNZZb1RarVvAB1vUeUU4cV7sTLU',
    appId: '1:741474883595:ios:fa02471a25c51360e54f0e',
    messagingSenderId: '741474883595',
    projectId: 'fruit-hub-756d3',
    storageBucket: 'fruit-hub-756d3.firebasestorage.app',
    iosBundleId: 'com.example.fruitApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBweHeVeM1eBoxNdzCpamp6_iUhKxgWEzk',
    appId: '1:741474883595:web:140e6549ae321599e54f0e',
    messagingSenderId: '741474883595',
    projectId: 'fruit-hub-756d3',
    authDomain: 'fruit-hub-756d3.firebaseapp.com',
    storageBucket: 'fruit-hub-756d3.firebasestorage.app',
    measurementId: 'G-CV10E1QGXC',
  );
}
